name: Deploy to S3 and Start SageMaker Studio

on:
  push:
    branches:
      - main  # Change this to the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install awscli boto3

      - name: Upload Notebooks to S3 and Start SageMaker Studio
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: justin-automation-output
          S3_KEY_PREFIX: notebooks
          DOMAIN_NAME: JustinTest  # Updated domain name
          DOMAIN_ID: d-gvaj2xo6gt7b  # Updated domain ID
          USER_PROFILE_NAME: justin  # Updated user profile name
          ROLE_ARN: arn:aws:iam::728939754004:role/service-role/SageMaker-MLOps
        run: python manage_sagemaker_studio.py
