name: Deploy to S3 and Start SageMaker Studio

on:
  push:
    branches:
      - main  # Change this to the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install awscli boto3

      - name: Upload Notebooks to S3 and Start SageMaker Studio
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: justin-automation-output
          S3_KEY_PREFIX: notebooks
          DOMAIN_ID: justin-test-sagemaker-studio-domain
          USER_PROFILE_NAME: justin-test-sagemaker-studio-user
          ROLE_ARN: arn:aws:iam::728939754004:role/service-role/SageMaker-MLOps
          SUBNET_IDS: subnet-016229a0a23943e74  # Replace with your actual Subnet IDs
          VPC_ID: vpc-086865caa3938cd2e  # Replace with your actual VPC ID
        run: python manage_sagemaker_studio.py
