name: Deploy to S3 and Start SageMaker Studio

on:
  push:
    branches:
      - main  # Change this to the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install awscli boto3

      - name: Upload Notebooks to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: justin-automation-output
          S3_KEY_PREFIX: notebooks
        run: python manage_sagemaker_studio.py

      - name: Create Lifecycle Configuration
        run: |
          base64 sync_notebooks.sh | tr -d '\n' > sync_notebooks_base64.sh
          aws sagemaker create-notebook-instance-lifecycle-config \
            --notebook-instance-lifecycle-config-name "SyncNotebooksLifecycleConfig" \
            --on-start Content=$(cat sync_notebooks_base64.sh)

      - name: Update SageMaker Studio User Profile
        run: |
          aws sagemaker update-user-profile \
            --domain-id d-1c32der6qazn \
            --user-profile-name JustinTestProfile \
            --user-settings "LifecycleConfigArns=arn:aws:sagemaker:${{ secrets.AWS_REGION }}:728939754004:notebook-instance-lifecycle-config/SyncNotebooksLifecycleConfig"
